name = "pol" # あなたのプロジェクト名に合わせる
# main = "src/index.ts" # Next.js連携の場合、Functionsを使うため不要なことが多い
compatibility_date = "2023-11-21" # wrangler suggest-compat-date で推奨される日付を確認
pages_build_output_dir = "./out" # Example for Next.js static export or other frameworks
# KV Namespace Binding (重要: IDを自分のものに置き換える)
[[kv_namespaces]]
binding = "TIMELINE_CACHE"
id = "bf140506011a49e59e39f91a6969f284"
preview_id = "bf140506011a49e59e39f91a6969f284" # previewでも同じIDを使う

# Variables for regions and instances (重要: 実際のインスタンスドメインに置き換える)
[vars]

[vars.regions]
# 例: 実際の信頼できる公開タイムラインを持つインスタンスに置き換えてください
# 複数指定する場合はカンマ区切り
DE = "mastodon.social,chaos.social"
FR = "mastodon.social,mamot.fr"
UK = "mastodon.social,mastodon.me.uk"
ES = "mastodon.social,mastodon.eus"
EU = "mastodon.social,mastodon.world"